version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.5
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /home/core/volumes/influxdb:/var/lib/influxdb
    restart: always  
